package source;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abj
 */
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.TableColumn;
public class TimeWindowOld extends javax.swing.JFrame {

    private String[] boatNames;
    private Controller con;
    private int selectedRowIndex, selectedColumIndex;
    private String[][] arr;
    
    public TimeWindowOld(String[] boatNames, Controller con) {
        this.boatNames = boatNames;
        this.con = con;
        String[][]  arr = con.convertBoatList();
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jButton2.setText("Start/Stop tid");
        
        
        DefaultTableModel tableModel = new DefaultTableModel(con.convertBoatList(), new String [] {
                "Nummer", "Navn", "Skipper", "Tid 1", "Tid 2", "Tidsforskel"
            }) {

                @Override
                public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
                }
            };
        jTable2.setModel(tableModel);
        jTable2.getSelectionModel().addSelectionInterval(0, 0);
        
        
        
        jTable2.addKeyListener(new KeyAdapter() {
         public void keyPressed(KeyEvent e) {
           int key = e.getKeyCode();
           if (key == KeyEvent.VK_ENTER || key == KeyEvent.VK_SPACE) {   
              startStopTime();
              }
           }
         }
      );
      
        int width = 80;
        for(int i = 0; i < 6; i++){
            int vColIndex = i; 
            TableColumn col = jTable2.getColumnModel().getColumn(vColIndex);
            col.setMinWidth(width);
            col.setMaxWidth(width);
            col.setPreferredWidth(width);  
        }
         
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kapsejlads");

        jButton1.setText("Afslut og Gem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            con.convertBoatList(),
            new String [] {
                "Nummer", "Navn", "Skipper", "Tid 1", "Tid 2"
            }
        ));
        jTable2.setRowHeight(18);
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(240, 240, 240)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton1)
                            .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(75, 75, 75)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1)))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            con.printTime();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        startStopTime();
    
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void startStopTime(){
        // T private void startStopTime(int selectedRowIndex){
        selectedRowIndex = jTable2.getSelectedRow();
        boolean b = con.TimeOnBoat(selectedRowIndex);
        if(b){
            //jButton3.setText("Stop tid");
            //jLabel2.setText("Startede tidstagning på " + con.boatList.get(selectedRowIndex).getName() + " - " + con.boatList.get(selectedRowIndex).getCaptain());
            if(con.boatList.get(selectedRowIndex).firstLap())
                jTable2.setValueAt("Kører", selectedRowIndex, 3);
            else
                jTable2.setValueAt("Kører", selectedRowIndex, 4);
            
        }
        if(!b){
            if(con.boatList.get(selectedRowIndex).firstLap()){
                jTable2.setValueAt(con.boatList.get(selectedRowIndex).getTime(0), selectedRowIndex, 3);
            }
            else{
                jTable2.setValueAt(con.boatList.get(selectedRowIndex).getTime(1), selectedRowIndex, 4);
                jTable2.setValueAt(con.boatList.get(selectedRowIndex).findTimeDiff(), selectedRowIndex, 5);
                }
            }
    }

   
    
    
   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
